name: Issue Detector
on:
    issues:
        types: [opened]
jobs:
    issue-info:
        runs-on: ubuntu-latest
        steps:
            - name: Print Issue
              run: |
                  echo "${{ github.event.issue.title }}"
                  echo "${{ github.event.issue.body }}"
                  echo "${{ github.event.issue.created_at }}"
                  echo "author: ${{ github.event.issue.user.login }}"
